#ifndef _FREQMOD_H_
#define _FREQMOD_H_ 
#include <config.h>
#include <freqmod_API.h>

#define MAX_CORE_VALIE MAKE_CORE_VALUE_FROM_FREQ(MAX_CORE_FREQ/10.0)
#define MAX_UNCORE_VALIE MAKE_UNCORE_VALUE_BY_FREQ(MAX_UNCORE_FREQ)
#define MIN_CORE_VALIE MAKE_CORE_VALUE_FROM_FREQ(MIN_CORE_FREQ/10.0)
#define MIN_UNCORE_VALIE MAKE_UNCORE_VALUE_BY_FREQ(MIN_UNCORE_FREQ)

#endif