all:
	chmod +x paett-inst-clang
	chmod +x paett-inst-clang++
	chmod +x paett-inst-flang
	chmod +x paett-opt-clang
	chmod +x paett-opt-clang++
	chmod +x paett-opt-flang
	chmod +x paett-regopt-clang
	chmod +x paett-regopt-clang++
	chmod +x paett-regopt-flang
	chmod +x freq_search_region
	chmod +x freq_search
	chmod +x freq_predict
	chmod +x collect_data
	chmod +x pretrain
