all:
	chmod +x paett-inst-clang
	chmod +x paett-inst-clang++
	chmod +x paett-inst-flang
	chmod +x paett-opt-clang
	chmod +x paett-opt-clang++
	chmod +x paett-opt-flang
	chmod +x freq_search
	chmod +x freq_predict
	chmod +x collect_data