#!/bin/bash
# for region-based frequency modification, we use instrumentation pass to insert function calls to freqmod library without CCT collection
if [[ "$@" =~ " -c" || "$@" =~ " -MM" ]]; then
  clang -g -Xclang -paett-freqmod $@
else
  clang -g -Xclang -paett-freqmod -lpaett_freqmod -lx86_adapt -L`dirname $0`/../lib $@
fi
